skip_commits:
  message: /Updated (readme|docs).*|!skipci/

skip_branch_with_pr: true

image: Visual Studio 2017

clone_folder: C:\projects\PSSpeedTest

environment:
  NugetApiKey:
    secure: kOgZxMM1AhKYpVnXZzLb/0xSMX68V/484bi3hCp5ZWsqjpuWBvGw8e5/6Uyw5aGb

cache:
  - _build_dependencies_ -> *.Depend.psd1

build: off

build_script:
  - ps: '& .\build.ps1 -Task Build'

test_script:
  - ps: '& .\build.ps1 -Task Test'

deploy_script:
  - ps: '& .\build.ps1 -Task Deploy'

on_finish:
  - ps: 7z a build.zip output; Get-ChildItem -Path '.\output' -Recurse | % { Push-AppveyorArtifact $_.FullName }