skip_commits:
  message: /Updated (readme|docs).*|!skipci/

skip_branch_with_pr: true

image: Visual Studio 2017

clone_folder: C:\projects\PSSpeedTest

environment:
  NugetApiKey:
    secure: kOgZxMM1AhKYpVnXZzLb/0xSMX68V/484bi3hCp5ZWsqjpuWBvGw8e5/6Uyw5aGb

cache:
  - _build_dependencies_ -> *.Depend.psd1

build: off

test_script:
  - ps: '& .\build.ps1'

artifacts:
  - path: output